#! /bin/sh -vx
prcs-synch --proj=Guis --ssh=basile@ours.starynkevitch.net --ssh-opts=-C --debug=2
prcs checkout -f
prcs rekey -f
# $ProjectHeader: Guis 1.62 Thu, 30 Dec 2004 14:14:05 +0100 basile $
# eof $Id: synchit 1.1 Wed, 19 May 2004 11:15:44 +0200 basile $

